# Below entries only valid for week 2 project
#spring.application.name=springmvc
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update

#Below entries are for week3 spring boot data jpa project

spring.application.name=springmvc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



